pipeline {
    agent any

    environment {
        // Set environment variables
        TOMCAT_HOME = '/Users/murugat/Desktop/hcv/azure_devops/apache-tomcat-9.0.98'  // Update with your Tomcat path
        TOMCAT_DEPLOY_DIR = "${TOMCAT_HOME}/webapps"
        WAR_FILE_NAME = 'try-devops-1.0.war'  // Update with your WAR file name
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                sh '''
                   git clone https://github.com/thangacodes/Java-project.git
                   ls -lrt
                   pwd
                   '''
            }
        }

        stage('Change Directory') {
            steps {
                // Changing to the directory where java code is available
                sh '''
                    cd webapp_build
                    ls -lrth
                '''
            }
        }

        stage('Compile and Build WAR') {
            steps {
                script {
                    // Run Maven to compile and build the WAR file
                    sh '''
                        cd webapp_build
                        ls -lrth
                        mvn clean package
                    '''
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                script {
                    // Copy the WAR file to Tomcat's webapps directory
                    sh """
                    cp target/${WAR_FILE_NAME} ${TOMCAT_DEPLOY_DIR}/
                    """
                }
            }
        }

        stage('Restart Tomcat') {
            steps {
                script {
                    // Restart Tomcat to deploy the new WAR
                    sh """
                    ${TOMCAT_HOME}/bin/shutdown.sh
                    sleep 5  // Wait for Tomcat to shut down
                    ${TOMCAT_HOME}/bin/startup.sh
                    """
                }
            }
        }

        stage('Test Deployment') {
            steps {
                script {
                    // Wait for Tomcat to fully start, then test deployment
                    sleep 15  // Wait for Tomcat to fully start (you can adjust the time)
                    sh 'curl http://localhost:8090/try-devops-1.0'  // Update with your app URL and correct port
                }
            }
        }
    }
    post {
        always {
            // Clean up resources if necessary
            echo 'Cleaning up...'
        }
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed. Check the logs.'
        }
    }
}
