pipeline {
    agent any
    environment {
        // Set environment variables
        TOMCAT_PATH = "${TOMCAT_HOME}/webapps"
        WAR_FILE = "try-devops-1.0.war"
        MAVEN_HOME = "/opt/homebrew/Cellar/maven/3.9.9/libexec/bin"
        TOMCAT_HOME = "/Users/td/Desktop/hcv/azure_devops/apache-tomcat-9.0.98"
        WEBAPP_BUILD_PATH = "webapp_build"
    }
    parameters {
        string(name: 'REPO_URL', defaultValue: 'https://github.com/thangacodes/Java-project.git', description: 'Git repository URL')
        string(name: 'WAR_FILE_PATH', defaultValue: 'webapp_build/target/${WAR_FILE}', description: 'Path to the WAR file')
        string(name: 'TOMCAT_STARTUP_SCRIPT', defaultValue: "${TOMCAT_HOME}/bin/startup.sh", description: 'Path to Tomcat startup script')
        string(name: 'TOMCAT_SHUTDOWN_SCRIPT', defaultValue: "${TOMCAT_HOME}/bin/shutdown.sh", description: 'Path to Tomcat shutdown script')
        string(name: 'TOMCAT_PORT', defaultValue: '8090', description: 'Tomcat server port for testing deployment')
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                sh '''
                   git clone ${REPO_URL}
                   ls -lrt
                   pwd
                   echo "Who is the executor of this task?:" $(whoami)
                   '''
            }
        }
        stage('Change Directory') {
            steps {
                // Changing to the directory where java code is available
                sh '''
                    cd ${WEBAPP_BUILD_PATH}
                    ls -lrth
                   '''
            }
        }
        stage('Compile and Build WAR') {
            steps {
                script {
                    // Run Maven to compile and build the WAR file
                    sh '''
                        cd ${WEBAPP_BUILD_PATH}
                        ls -lrth
                        echo "Going to perform maven compilation.."
                        ${MAVEN_HOME}/mvn clean package
                        pwd
                        ls -lrth
                       '''
                }
            }
        }
        stage('Deploy to Tomcat') {
            steps {
                script {
                    // Copy the WAR file to Tomcat's webapps dir
                    sh """
                    cp ${WAR_FILE_PATH} ${TOMCAT_PATH}
                    echo "Going to check the path.."
                    ls -lrth ${TOMCAT_PATH}
                    """
                }
            }
        }
        stage('Restart Tomcat') {
            steps {
                script {
                    sh """
                    echo "Going to list out the files in ${TOMCAT_PATH}"
                    ls -lrt ${TOMCAT_PATH}
                    sleep 5
                    echo "........"
                    echo "Going to start Apache Tomcat service"
                    echo "........"
                    sh ${TOMCAT_STARTUP_SCRIPT}
                    echo "........"
                    echo "Sleeping for 200 seconds..."
                    sleep 200
                    echo "........"
                    echo "Going to stop Apache Tomcat service"
                    echo "........"
                    sh ${TOMCAT_SHUTDOWN_SCRIPT}
                    """
                }
            }
        }
        stage('Test Deployment') {
            steps {
                script {
                    sleep 120
                    sh "curl http://localhost:${TOMCAT_PORT}/try-devops-1.0/"
                }
            }
        }
    }
    post {
        always {
            // Clean up resources if necessary
            echo 'Cleaning up...'
        }
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed. Check the logs.'
        }
    }
}
